
# cargo-vet config file

[policy.protoc-gen-prost]
audit-as-crates-io = false

[policy.protoc-gen-prost-crate]
audit-as-crates-io = false

[policy.protoc-gen-prost-serde]
audit-as-crates-io = false

[policy.protoc-gen-prost-validate]
audit-as-crates-io = false

[policy.protoc-gen-tonic]
audit-as-crates-io = false

[[exemptions.anyhow]]
version = "1.0.66"
criteria = "safe-to-deploy"

[[exemptions.autocfg]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.bytes]]
version = "1.2.1"
criteria = "safe-to-deploy"

[[exemptions.cfg-if]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.either]]
version = "1.8.0"
criteria = "safe-to-deploy"

[[exemptions.fastrand]]
version = "1.8.0"
criteria = "safe-to-deploy"

[[exemptions.fixedbitset]]
version = "0.4.2"
criteria = "safe-to-deploy"

[[exemptions.hashbrown]]
version = "0.12.3"
criteria = "safe-to-deploy"

[[exemptions.heck]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.indexmap]]
version = "1.9.1"
criteria = "safe-to-deploy"

[[exemptions.instant]]
version = "0.1.12"
criteria = "safe-to-deploy"

[[exemptions.itertools]]
version = "0.10.5"
criteria = "safe-to-deploy"

[[exemptions.lazy_static]]
version = "1.4.0"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.137"
criteria = "safe-to-deploy"

[[exemptions.log]]
version = "0.4.17"
criteria = "safe-to-deploy"

[[exemptions.multimap]]
version = "0.8.3"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.16.0"
criteria = "safe-to-deploy"

[[exemptions.pbjson-build]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.petgraph]]
version = "0.6.2"
criteria = "safe-to-deploy"

[[exemptions.prettyplease]]
version = "0.1.21"
criteria = "safe-to-deploy"

[[exemptions.proc-macro2]]
version = "1.0.47"
criteria = "safe-to-deploy"

[[exemptions.prost]]
version = "0.11.2"
criteria = "safe-to-deploy"

[[exemptions.prost-build]]
version = "0.11.2"
criteria = "safe-to-deploy"

[[exemptions.prost-derive]]
version = "0.11.2"
criteria = "safe-to-deploy"

[[exemptions.prost-types]]
version = "0.11.2"
criteria = "safe-to-deploy"

[[exemptions.quote]]
version = "1.0.21"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.regex]]
version = "1.7.0"
criteria = "safe-to-deploy"

[[exemptions.regex-syntax]]
version = "0.6.28"
criteria = "safe-to-deploy"

[[exemptions.remove_dir_all]]
version = "0.5.3"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "1.0.103"
criteria = "safe-to-deploy"

[[exemptions.tempfile]]
version = "3.3.0"
criteria = "safe-to-deploy"

[[exemptions.tonic-build]]
version = "0.8.2"
criteria = "safe-to-deploy"

[[exemptions.unicode-ident]]
version = "1.0.5"
criteria = "safe-to-deploy"

[[exemptions.which]]
version = "4.3.0"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

